# HTTP — ACME challenge + redirection HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name sombateka.cd www.sombateka.cd api.sombateka.cd;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location /healthz {
        proxy_pass http://backend/healthz;
        access_log off;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
